# Port exhibition
server:
  port: ${SERVER_PORT:8090}

# spring boot configurations
spring:
  application:
    name: vg.ms.enrollment
  data:
    mongodb:
      uri: mongodb+srv://amirarbieto:n1230IGFtm6682Kj@artemiosolutions.pripjnm.mongodb.net/artemiosolutions?retryWrites=true&w=majority

# Microservice health meter
management:
  endpoint:
    health:
      show-details: always

# Endpoint de actuator

api:
  version: api/v1

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/enrollment

# External services
services:
  student:
    url: ${STUDENT_SERVICE_URL:https://ms-vg-student-production.up.railway.app/public/api/v1/ubigeo/}